routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('pegawai.index');
    });    
    Route::get('pegawai/pdf', 'PegawaiController@pdf')->name('pegawai-pdf');
    Route::resource('/pegawai', 'PegawaiController');    
    Route::resource('/pendidikan', 'PendidikanController');
    Route::resource('/pelatihan', 'PelatihanController');
    Route::resource('/pengalaman', 'PengalamanController');    
    Route::resource('/agama', 'AgamaController');
    Route::resource('/negara', 'NegaraController');
    Route::resource('/darah', 'DarahController');
    Route::resource('/keluarga', 'KeluargaController');
    Route::resource('/chart', 'ChartController');
    Route::resource('pegawai.pendidikan', 'PendidikanController');
    Route::get('pegawai/pendidikan/{id}','PendidikanController@pel');
    Route::resource('pegawai.pelatihan', 'PelatihanController');
    Route::get('pegawai/pelatihan/{id}','PelatihanController@pel');
    Route::resource('pegawai.pengalaman', 'PengalamanController');
    Route::get('pegawai/pengalaman/{id}','PengalamanController@pel');
    Route::get('/home', 'HomeController@index')->name('home');
});

Auth::routes();

app/Negara.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Negara extends Model
{
    //
    protected $table='tbl_negara';
    protected $primaryKey='id_ngr';
    public $timestamps = false;

    public function pegawai()
    {
       return $this->hasMany('App\Pegawai'); 
    }
}

app/Http/Controllers/NegaraController.php
<?php

namespace App\Http\Controllers;

use App\Negara;
use Illuminate\Http\Request;

class NegaraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $negara =Negara::all();
        return view('negara.tampil', compact('negara'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('negara.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $negara = new Negara;
        $negara-> nm_negara = $request ->nm_negara;
        $negara-> save();

        return redirect ('negara');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $negara =Negara::find($id);
        return view('negara.edit', compact('negara'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $negara = \App\Negara::find($id);
        $negara-> nm_negara = $request ->nm_negara;
        $negara-> save();

        return redirect ('negara');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $negara = Negara::find($id);
        $negara->delete();

        return redirect('negara');
    }
}

resources/views/negara/create.blade.php
@section('title')
Tambah Negara
@endsection
@section('master')
active
@endsection
@extends('app')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Tambah Negara</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="/negara">Kewarganegaraan</a></li>
          <li class="breadcrumb-item"><a href="#">Tambah Negara</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{url('/negara')}}" method="post">
                {{ csrf_field()}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama Negara</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" name="nm_negara">
                  </div>

              </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Tambah</button>
                  <a class="btn btn-secondary" href="/negara"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/negara/edit.blade.php
@section('title')
Edit Negara
@endsection
@section('master')
active
@endsection
@extends('app')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Edit Negara</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="/negara">Kewarganegaraan</a></li>
          <li class="breadcrumb-item"><a href="#">Edit Negara</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{route('negara.update', $negara->id_ngr)}}" method="post">
                {{ csrf_field()}} 
                {{ method_field('PUT')}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama Negara</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" value="{{$negara->nm_negara}}" name="nm_negara">
                  </div>

              </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Edit</button>
                  <a class="btn btn-secondary" href="/negara"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/negara/tampil.blade.php
@section('title')
Master Kewarganegaraan
@endsection
@section('master')
active
@endsection
@extends('app')
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i> Master Kewarganegaraan</h1>
          <!-- <p>Bootstrap Components</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="#">Kewarganegaraan</a></li>
        </ul>
      </div>
      <!-- Buttons-->
      <div class="tile mb-4">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
              <!-- <h2 class="mb-3 line-head" id="buttons">Data Pegawai</h2> -->
              <div class="form-group col-md 8">              
              <a href="{{route('negara.create')}}"
              class="btn btn-primary"><span class="fa fa-plus"> Tambah Negara</span></a>
              </div>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Negara</th>                      
                      <th>Operasi</th>                      
                    </tr>
                  </thead>
                  <tbody>
                  @php
                  $no_urut=1;
                  @endphp
                    @foreach($negara as $tampil)
                    <tr>
                      <td>{{$no_urut++}}</td>
                      <td>{{$tampil->nm_negara}}</td>                     
                      <td>
                        <a href="{{route('negara.edit', $tampil->id_ngr)}}"
                        class="btn btn-info"><span class="fa fa-edit (alias)"> Edit</span></a>

                      </td>
                      <td>
                        <form action="{{route('negara.destroy', $tampil->id_ngr)}}" method="post">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <button class="btn btn-danger" type="submit" ><span class="fa fa-trash"> Hapus</span></button>
                        </form>
                      </td>
                      
                    </tr>
                    @endforeach
                    
                  </tbody>
                </table>           
          

            </div>            
          </div>
        </div>
        <div class="row">      
          
        </div>
      </div>
    </main>
@endsection