routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('pegawai.index');
    });    
    Route::get('pegawai/pdf', 'PegawaiController@pdf')->name('pegawai-pdf');
    Route::resource('/pegawai', 'PegawaiController');    
    Route::resource('/pendidikan', 'PendidikanController');
    Route::resource('/pelatihan', 'PelatihanController');
    Route::resource('/pengalaman', 'PengalamanController');    
    Route::resource('/agama', 'AgamaController');
    Route::resource('/negara', 'NegaraController');
    Route::resource('/darah', 'DarahController');
    Route::resource('/keluarga', 'KeluargaController');
    Route::resource('/chart', 'ChartController');
    Route::resource('pegawai.pendidikan', 'PendidikanController');
    Route::get('pegawai/pendidikan/{id}','PendidikanController@pel');
    Route::resource('pegawai.pelatihan', 'PelatihanController');
    Route::get('pegawai/pelatihan/{id}','PelatihanController@pel');
    Route::resource('pegawai.pengalaman', 'PengalamanController');
    Route::get('pegawai/pengalaman/{id}','PengalamanController@pel');
    Route::get('/home', 'HomeController@index')->name('home');
});

Auth::routes();

app/Keluarga.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Keluarga extends Model
{
    //
    protected $table='tbl_statusk';
    protected $primaryKey='kdstatusk';
    public $timestamps = false;

    public function pegawai()
    {
       return $this->hasMany('App\Pegawai'); 
    }
}

app/Http/Controllers/KeluargaController.php
<?php

namespace App\Http\Controllers;

use App\Keluarga;
use Illuminate\Http\Request;

class KeluargaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $keluarga =Keluarga::all();
        return view('keluarga.tampil', compact('keluarga'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('keluarga.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $keluarga = new keluarga;
        $keluarga-> nmstatusk = $request ->status;
        $keluarga-> save();

        return redirect ('keluarga');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Keluarga  $keluarga
     * @return \Illuminate\Http\Response
     */
    public function show(Keluarga $keluarga)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Keluarga  $keluarga
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $keluarga =Keluarga::find($id);
        return view('keluarga.edit', compact('keluarga'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Keluarga  $keluarga
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $keluarga = \App\Keluarga::find($id);
        $keluarga-> nmstatusk = $request ->status;
        $keluarga-> save();

        return redirect ('keluarga');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Keluarga  $keluarga
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $keluarga = Keluarga::find($id);
        $keluarga->delete();

        return redirect('keluarga');
    }
}

resources/views/keluarga/create.blade.php
@section('title')
Tambah Status Keluarga
@endsection
@section('master')
active
@endsection
@extends('app')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Tambah Status Keluarga</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Keluarga</li>
          <li class="breadcrumb-item"><a href="/keluarga">Status Keluarga</a></li>
          <li class="breadcrumb-item"><a href="#">Tambah Status Keluarga</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{url('/keluarga')}}" method="post">
                {{ csrf_field()}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">Status</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" name="status">
                  </div>
                </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Tambah</button>
                  <a class="btn btn-secondary" href="/keluarga"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/keluarga/edit.blade.php
@section('title')
Edit Status Keluarga
@endsection
@section('master')
active
@endsection
@extends('app')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Edit Status Keluarga</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="/keluarga">Status Keluarga</a></li>
          <li class="breadcrumb-item"><a href="#">Edit Status Keluarga</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{route('keluarga.update', $keluarga->kdstatusk)}}" method="post">
                {{ csrf_field()}} 
                {{ method_field('PUT')}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">Status</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" value="{{$keluarga->nmstatusk}}" name="status">
                  </div>
                </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Edit</button>
                  <a class="btn btn-secondary" href="/keluarga"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/keluarga/tampil.blade.php
@section('title')
Master Status Keluarga
@endsection
@section('master')
active
@endsection
@extends('app')
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i> Master Status Keluarga</h1>
          <!-- <p>Bootstrap Components</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Tabel Master</li>
          <li class="breadcrumb-item"><a href="#">Status Keluarga</a></li>
        </ul>
      </div>
      <!-- Buttons-->
      <div class="tile mb-4">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
              <!-- <h2 class="mb-3 line-head" id="buttons">Data Pegawai</h2> -->
              <div class="form-group col-md 8">              
              <a href="{{route('keluarga.create')}}"
              class="btn btn-primary"><span class="fa fa-plus"> Tambah Status</span></a>
              </div>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Status</th>                                                          
                      <th>Operasi</th>                      
                    </tr>
                  </thead>
                  <tbody>
                  @php
                  $no_urut=1;
                  @endphp
                    @foreach($keluarga as $tampil)
                    <tr>
                      <td>{{$no_urut++}}</td>
                      <td>{{$tampil->nmstatusk}}</td>                     
                      <td>
                        <a href="{{route('keluarga.edit', $tampil->kdstatusk)}}"
                        class="btn btn-info"><span class="fa fa-edit (alias)"> Edit</span></a>

                      </td>
                      <td>
                        <form action="{{route('keluarga.destroy', $tampil->kdstatusk)}}" method="post">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <button class="btn btn-danger" type="submit" ><span class="fa fa-trash"> Hapus</span></button>
                        </form>
                      </td>
                      
                    </tr>
                    @endforeach
                    
                  </tbody>
                </table>           
          

            </div>            
          </div>
        </div>
        <div class="row">      
          
        </div>
      </div>
    </main>
@endsection