routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('pegawai.index');
    });    
    Route::get('pegawai/pdf', 'PegawaiController@pdf')->name('pegawai-pdf');
    Route::resource('/pegawai', 'PegawaiController');    
    Route::resource('/pendidikan', 'PendidikanController');
    Route::resource('/pelatihan', 'PelatihanController');
    Route::resource('/pengalaman', 'PengalamanController');    
    Route::resource('/agama', 'AgamaController');
    Route::resource('/negara', 'NegaraController');
    Route::resource('/darah', 'DarahController');
    Route::resource('/keluarga', 'KeluargaController');
    Route::resource('/chart', 'ChartController');
    Route::resource('pegawai.pendidikan', 'PendidikanController');
    Route::get('pegawai/pendidikan/{id}','PendidikanController@pel');
    Route::resource('pegawai.pelatihan', 'PelatihanController');
    Route::get('pegawai/pelatihan/{id}','PelatihanController@pel');
    Route::resource('pegawai.pengalaman', 'PengalamanController');
    Route::get('pegawai/pengalaman/{id}','PengalamanController@pel');
    Route::get('/home', 'HomeController@index')->name('home');
});

Auth::routes();

app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    //
    protected $table='pegawai';
    protected $fillable = [
    'nip',
    'nama',
    'tmpt_lahir',
    'tgl_lahir',
    'jenis_kelamin',
    'alamat',   
    'foto',
    'nohp',    
    'created_at',
    'updated_at'
    ];

    public function agama()
    {
       return $this->belongsTo('App\Agama', 'agama_id', 'id_agm'); 
    }
    public function negara()
    {
       return $this->belongsTo('App\Negara', 'negara_id', 'id_ngr'); 
    }
    public function darah()
    {
       return $this->belongsTo('App\Darah', 'gol_darah_id', 'id_darah'); 
    }
    public function keluarga()
    {
       return $this->belongsTo('App\Keluarga', 'skeluarga_id', 'kdstatusk'); 
    }

    public function pendidikan()
    {
       return $this->hasMany('App\Pendidikan'); 
    }
    
    public function Pelatihan()
    {
       return $this->hasMany('App\Pelatihan'); 
    }
    
    public function Pengalaman()
    {
       return $this->hasMany('App\Pengalaman'); 
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Pegawai;
use App\Agama;
use App\Negara;
use App\Darah;
use App\Keluarga;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade as PDF;


class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // dd('masuk');
        $pegawai=Pegawai::all();
        return view('pegawai.tampil', compact('pegawai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $agama =Agama::all();
        $negara =Negara::all();
        $darah =Darah::all();
        $keluarga =Keluarga::all();
        return view('pegawai.tambah' , compact('agama', 'negara', 'darah', 'keluarga'));
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd('msk');
        $pegawai = new Pegawai;
        $pegawai->nip = $request ->nip;
        $pegawai->nama = $request ->nama;
        $pegawai->tmpt_lahir = $request ->tmpt_lahir;
        $pegawai->tgl_lahir = $request ->tgl_lahir;
        $pegawai->jenis_kelamin = $request ->jenis_kelamin;
        $pegawai->agama_id = $request ->agama_id;
        $pegawai->negara_id = $request ->negara_id;
        $pegawai->gol_darah_id = $request ->gol_darah_id;
        $pegawai->skeluarga_id = $request ->skeluarga_id;
        $pegawai->alamat = $request ->alamat;        
        $pegawai->foto = $request ->foto;
        $pegawai->nohp = $request ->nohp;        
        
        $pegawai->save();
        return redirect ('pegawai');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $pegawai = Pegawai::find($id);
        return view ('pegawai.show', compact('pegawai'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        
        $pegawai = Pegawai::find($id);
        $agama =Agama::all();
        $negara =Negara::all();
        $darah =Darah::all();
        $keluarga =Keluarga::all();
        return view ('pegawai.edit', compact('pegawai', 'agama', 'negara', 'darah', 'keluarga'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $pegawai = \App\Pegawai::find($id);
        $pegawai->nip = $request ->nip;
        $pegawai->nama = $request ->nama;
        $pegawai->tmpt_lahir = $request ->tmpt_lahir;
        $pegawai->tgl_lahir = $request ->tgl_lahir;
        $pegawai->jenis_kelamin = $request ->jenis_kelamin;
        $pegawai->agama_id = $request ->agama_id;
        $pegawai->negara_id = $request ->negara_id;
        $pegawai->gol_darah_id = $request ->gol_darah_id;
        $pegawai->skeluarga_id = $request ->skeluarga_id;
        $pegawai->alamat = $request ->alamat;        
        $pegawai->foto = $request ->foto;
        $pegawai->nohp = $request ->nohp;  
        $pegawai->save();  


        return redirect('pegawai');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $pegawai = Pegawai::find($id);
        $pegawai->delete();

        return redirect('pegawai');
    }
    public function pdf()
    {
        $pegawai=Pegawai::all();
        $pdf = PDF::loadView('pegawai.pdf', ['pegawai'=>$pegawai]);
        return $pdf->download('pegawai.pdf');
    }
}

resources/views/pegawai/edit.blade.php
@extends('app')
@section('title')
Edit Pegawai
@endsection
@section('pegawai')
active
@endsection
@section('content')
<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Edit Pegawai</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="#">Edit Pegawai</a></li>
        </ul>
      </div>

      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <form class="form-horizontal" action="{{route('pegawai.update', $pegawai->id)}}" method="post">
              {{csrf_field()}}
              {{method_field('PUT')}}
                <div class="form-group row">
                    <label class="control-label col-md-3">NIP</label>
                    <div class="col-md-8">
                      <input class="form-control col-md-8" type="number" name="nip" value="{{$pegawai->nip}}">
                    </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama</label>
                  <div class="col-md-8">
                    <input class="form-control" type="text" name="nama" value="{{$pegawai->nama}}">
                  </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-3">Tempat Lahir</label>
                    <div class="col-md-8">
                      <input class="form-control col-md-8" type="text" name="tmpt_lahir" value="{{$pegawai->tmpt_lahir}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-3">Tanggal Lahir</label>
                    <div class="col-md-8">
                        <input class="form-control col-md-8" type="date" name="tgl_lahir" value="{{$pegawai->tgl_lahir}}">
                    </div>
                </div>                                
                <div class="form-group row">
                  <label class="control-label col-md-3">Alamat</label>
                  <div class="col-md-8">
                    <textarea class="form-control" rows="4" name="alamat">{{$pegawai->alamat}}"</textarea>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Jenis Kelamin</label>
                  <div class="col-md-9">
                    <div class="form-check">
                      <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" value="L" {{$pegawai->jenis_kelamin == 'L' ? 'checked' : ''}}>Laki-laki
                      </label>
                    </div>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" value="P" {{$pegawai->jenis_kelamin == 'P' ? 'checked' : ''}}>Perempuan
                      </label>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Agama</label>
                    <div class="col-md-8">
                        <select class="form-control" name="agama_id" id="exampleSelect1">
                            @foreach($agama as $tampil)
                            <option value="{{$tampil->id_agm}}">{{$tampil->nmagama}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Kewarganegaraan</label>
                    <div class="col-md-8">
                        <select class="form-control" name="negara_id" id="exampleSelect1">
                            @foreach($negara as $tampil)
                            <option value="{{$tampil->id_ngr}}">{{$tampil->nm_negara}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Golongan Darah</label>
                    <div class="col-md-8">
                        <select class="form-control" name="gol_darah_id" id="exampleSelect1">
                            @foreach($darah as $tampil)
                            <option value="{{$tampil->id_darah}}">{{$tampil->nama_gol_darah}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                <div class="form-group row">
                  <label class="control-label col-md-3">Status</label>
                    <div class="col-md-8">
                        <select class="form-control" name="skeluarga_id" id="exampleSelect1">
                            @foreach($keluarga as $tampil)
                            <option value="{{$tampil->kdstatusk}}">{{$tampil->nmstatusk}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                <div class="form-group row">
                  <label class="control-label col-md-3">Foto</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="file" name="foto" value="{{$pegawai->foto}}">
                  </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-md-3">Nomor HP</label>
                    <div class="col-md-8">
                      <input class="form-control" type="number" name="nohp" value="{{$pegawai->nohp}}">
                    </div>
                </div>
                
              
            </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Edit</button>
                  <a class="btn btn-secondary" href="#"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              
            </div>
              </form>
          </div>
        </div>              
      </div>
</main>
@endsection

resources/views/pegawai/index.blade.php
@extends('app')
@section('title')
Dashboard
@endsection
@section('dashboard')
active
@endsection
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-dashboard"></i> Simpeg Dashboard</h1>
          <p>Dashboard Sistem Kepegawaian</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        </ul>
      </div>
        <div class="col-md-6 col-lg-3"><a href="{{route('pegawai.create')}}">
          <div class="widget-small info coloured-icon"><i class="icon fa fa-edit fa-3x"></i>
            <div class="info"></a>
              <h4>Tambah Pegawai</h4>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3"><a href="{{route('pegawai.index')}}">
          <div class="widget-small warning coloured-icon"><i class="icon fa fa-files-o fa-3x"></i>
            <div class="info"></a>
              <h4>Data Pegawai</h4>
            </div>
          </div>
        </div>
      </div>
    </main>
@endsection

resources/views/pegawai/show.blade.php
@extends('app')
@section('title')
Detail Pegawai
@endsection
@section('pegawai')
active
@endsection
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i> Detail Pegawai</h1>
          <!-- <p>Bootstrap Components</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="/pegawai">Data Pegawai</a></li>
          <li class="breadcrumb-item"><a href="#">Detail Pegawai</a></li>
        </ul>
      </div>			
      <!-- Buttons-->
      <div class="tile">
        <div class="page-header">
          <div class="row">
            <div class="col-md-12">   
						<img src="{{asset('imgpegawai/'.$pegawai->foto)}}" width="180px" height="120px" alt="">
            <table class="table-condensed">					
            	<tr>
			    			<td>NIP</td>
			    			<td>:</td>
			    			<td>{{$pegawai->nip}}</td>
		    			</tr>
							<tr>
								<td>Nama</td>
								<td>: </td>
                				<td>{{$pegawai->nama}}</td>
							</tr>
							<tr>
								<td> Tempat, Tanggal Lahir</td>
								<td>:</td>
								<td>{{$pegawai->tmpt_lahir}}, {{$pegawai->tgl_lahir}}</td>
							</tr>                               
							<tr>
								<td> Jenis Kelamin</td>
								<td>:</td>
								<td>{{$pegawai->jenis_kelamin}}</td>
							</tr>                               
							<tr>
								<td> Alamat</td>
								<td>:</td>
								<td>{{$pegawai->alamat}}</td>
							</tr>                               
							<tr>
								<td> Agama</td>
								<td>:</td>
								<td>{{$pegawai->agama->nmagama}}</td>
							</tr>                               
								<td> Kewarganegaraan</td>
								<td>:</td>
								<td>{{$pegawai->negara->nm_negara}}</td>
							</tr>                               
							</tr>                               
								<td> Golongan Darah</td>
								<td>:</td>
								<td>{{$pegawai->darah->nama_gol_darah}}</td>
							</tr>                               
							</tr>                               
								<td> Status</td>
								<td>:</td>
								<td>{{$pegawai->keluarga->nmstatusk}}</td>
							</tr>                               
							</tr>                               
								<td> Nomor HP</td>
								<td>:</td>
								<td>{{$pegawai->nohp}}</td>
							</tr>                               
						</table>
            </div>            
          </div>
        </div>
      </div>
      
<a href="/pegawai/{{$pegawai->id}}/pelatihan" class="btn btn-primary"><span> Pelatihan</span></a>
<a href="/pegawai/{{$pegawai->id}}/pendidikan" class="btn btn-primary"><span> Pendidikan</span></a>
<a href="/pegawai/{{$pegawai->id}}/pengalaman" class="btn btn-primary"><span> Pengalaman Kerja</span></a>
        
    </main>
@endsection

resources/views/pegawai/tambah.blade.php
@section('title')
Tambah Pegawai
@endsection
@section('pegawai')
active
@endsection
@extends('app')
@section('content')

<main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Tambah Pegawai</h1>
          <!-- <p>Sample forms</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="#">Tambah Pegawai</a></li>
        </ul>
      </div>
      
      <div class="row">        
        <div class="col-md-12">
          <div class="tile">
            <!-- <h3 class="tile-title">Register</h3> -->            
            <div class="tile-body">
              <!-- <form class="form-horizontal" action="{{route('pegawai.store')}}" method="post"> -->
              <form class="form-horizontal" action="{{url('/pegawai')}}" method="post">
                {{ csrf_field()}} 
                <div class="form-group row">
                  <label class="control-label col-md-3">NIP</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" name="nip">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Nama</label>
                  <div class="col-md-8">
                    <input class="form-control" type="text" name="nama">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Tempat Lahir</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="text" name="tmpt_lahir">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Tanggal Lahir</label>
                    <div class="col-md-8">
                      <input class="form-control col-md-8" type="date" name="tgl_lahir" >
                    </div>
                </div>                   
                <div class="form-group row">
                  <label class="control-label col-md-3">Alamat</label>
                  <div class="col-md-8">
                    <textarea class="form-control" rows="4" name="alamat"></textarea>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Jenis Kelamin</label>
                  <div class="col-md-9">
                    <div class="form-check">
                      <label class="form-check-label">
                        <input class="form-check-input" type="radio" value="L" name="jenis_kelamin">Laki-laki
                      </label>
                    </div>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input class="form-check-input" type="radio" value="P" name="jenis_kelamin">Perempuan
                      </label>
                    </div>
                  </div>
                </div>               
                <div class="form-group row">
                  <label class="control-label col-md-3">Agama</label>
                    <div class="col-md-8">
                        <select class="form-control" name="agama_id" id="exampleSelect1">
                            @foreach($agama as $tampil)
                            <option value="{{$tampil->id_agm}}">{{$tampil->nmagama}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Kewarganegaraan</label>
                    <div class="col-md-8">
                        <select class="form-control" name="negara_id" id="exampleSelect1">
                            @foreach($negara as $tampil)
                            <option value="{{$tampil->id_ngr}}">{{$tampil->nm_negara}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Golongan Darah</label>
                    <div class="col-md-8">
                        <select class="form-control" name="gol_darah_id" id="exampleSelect1">
                            @foreach($darah as $tampil)
                            <option value="{{$tampil->id_darah}}">{{$tampil->nama_gol_darah}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                <div class="form-group row">
                  <label class="control-label col-md-3">Status</label>
                    <div class="col-md-8">
                        <select class="form-control" name="skeluarga_id" id="exampleSelect1">
                            @foreach($keluarga as $tampil)
                            <option value="{{$tampil->kdstatusk}}">{{$tampil->nmstatusk}}</option> 
                            @endforeach                           
                        </select>
                    </div>                    
                </div>  
                
                <div class="form-group row">
                  <label class="control-label col-md-3">Foto</label>
                  <div class="col-md-8">
                    <input class="form-control col-md-8" type="file" name="foto">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="control-label col-md-3">Nomor HP</label>
                  <div class="col-md-8">
                    <input class="form-control" type="text" name="nohp">
                  </div>           
                </div>

            <div class="tile-footer">
              <div class="row">              
              <div class="col-md-8 col-md-offset-3">
                  <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Tambah</button>
                  <a class="btn btn-secondary" href="http://127.0.0.1:8000/pegawai"><i class="fa fa-fw fa-lg fa-times-circle"></i>Kembali</a>
                </div>        
                
              </div>
              </form>
            </div>

          </div>
        </div>               
      </div>
    </main>

@endsection

resources/views/pegawai/tampil.blade.php
@extends('app')
@section('title')
Data Pegawai
@endsection
@section('pegawai')
active
@endsection
@section('content')
    <main class="app-content">
      <div class="app-title">
        <div class="div">
          <h1><i class="fa fa-laptop"></i> Data Pegawai</h1>
          <!-- <p>Bootstrap Components</p> -->
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Pegawai</li>
          <li class="breadcrumb-item"><a href="#">Data Pegawai</a></li>
        </ul>
      </div>
      <!-- Buttons-->
      <div class="tile mb-4">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
              
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Foto</th>
                      <th>NIP</th>
                      <th>Nama</th>
                      <th>TTL</th>
                      <th>JK</th>
                      <th>No. Telp</th>
                      <th>More</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($pegawai as $tampil)
                    <tr>                      
                      <td><img src="{{asset('imgpegawai/'.$tampil->foto)}}" alt="" width="50px" height="50px"></td>
                      <td>{{$tampil->nip}}</td>
                      <td><a href="{{route('pegawai.show', $tampil->id)}}">{{$tampil->nama}}</a></td>
                      <td>{{$tampil->tmpt_lahir}}, {{$tampil->tgl_lahir}}</td>
                      <td>{{$tampil->jenis_kelamin}}</td>
                      <td>{{$tampil->nohp}}</td>
                      <td>
                        <a href="{{url('/pegawai/'.$tampil->id.'/edit')}}"
                        class="btn btn-info"><span class="fa fa-edit (alias)"></span></a>

                      </td>
                      <td>
                        <form action="{{route('pegawai.destroy', $tampil->id)}}" method="post">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <button class="btn btn-danger" type="submit" ><span class="fa fa-trash"></span></button>
                        </form>
                      </td>
                      
                    </tr>
                    @endforeach
                    
                  </tbody>
                </table>           
          

            </div>            
          </div>
        </div>
        <div class="row">      
          
        </div>
      </div>
    </main>
@endsection